# -*- coding: utf-8 -*-

<<<<<<< HEAD
# This file was automatically generated by parselglossy on 2026-02-13
=======
# This file was automatically generated by parselglossy on 2025-11-17
>>>>>>> added second molecule to input_parser; new embedding section in driver
# Editing is *STRONGLY DISCOURAGED*
