version: 2.1

variables:
  ubuntu-2404: &ubuntu-2404
    docker:
      - image: ghcr.io/mrchemsoft/metamr/circleci_ubuntu-24.04:sha-2b5887e
        name: tsubame
        user: merzbow
    working_directory: ~/mrchem
  configure-serial: &configure-serial
    run:
      name: Configuring serial
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=g++ \
          --prefix=$HOME/Software/MRChem
  configure-omp: &configure-omp
    run:
      name: Configuring OpenMP parallel
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=g++ \
          --omp \
          --prefix=$HOME/Software/MRChem-omp
  configure-mpi: &configure-mpi
    run:
      name: Configuring MPI parallel
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=mpicxx \
          --mpi \
          --prefix=$HOME/Software/MRChem-mpi
  build: &build
    run:
      name: Building and installing
      shell: /bin/bash
      command: |
        cmake --build build --target install -- VERBOSE=1 -j4
  tests-short: &tests-short
    run:
      name: Get assigned tests and run
      command: |
        : > test-list.txt
        TESTS=$(ctest -L "short" --test-dir build -N | sed -n 's/.*Test #[0-9]\+: \(.*\)/\1/p')
        echo "Tests found: $TESTS"
        echo "$TESTS" | circleci tests run \
          --command='>test-list.txt xargs echo' \
          --verbose
        if [ ! -s test-list.txt ]; then
          circleci-agent step halt
        else
          cat test-list.txt | tr " " "|" | xargs -I {} ctest --test-dir build --verbose --output-on-failure -R "^({})$"
        fi
  tests-medium: &tests-medium
    run:
      name: Get assigned tests and run
      command: |
        : > test-list.txt
        TESTS=$(ctest -L "medium" --test-dir build -N | sed -n 's/.*Test #[0-9]\+: \(.*\)/\1/p')
        echo "Tests found: $TESTS"
        echo "$TESTS" | circleci tests run \
          --command='>test-list.txt xargs echo' \
          --verbose
        if [ ! -s test-list.txt ]; then
          circleci-agent step halt
        else
          cat test-list.txt | tr " " "|" | xargs -I {} ctest --test-dir build --verbose --output-on-failure -R "^({})$"
        fi

# Run both the build and test stages
jobs:
###############################################################
# Building

  build-serial:
    <<: *ubuntu-2404
    steps:
      - checkout:
          method: blobless
      - *configure-serial
      - *build
      - persist_to_workspace:
          root: ~/mrchem
          paths:
            - .

  build-omp:
    <<: *ubuntu-2404
    steps:
      - checkout:
          method: blobless
      - *configure-omp
      - *build
      - persist_to_workspace:
          root: ~/mrchem
          paths:
            - .

  build-mpi:
    <<: *ubuntu-2404
    steps:
      - checkout:
          method: blobless
      - *configure-mpi
      - *build
      - persist_to_workspace:
          root: ~/mrchem
          paths:
            - .

###############################################################
# Testing

  test-serial-short:
    <<: *ubuntu-2404
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-short

  test-omp-short:
    <<: *ubuntu-2404
    parallelism: 4
    environment:
      OMP_NUM_THREADS: '2'
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-short

  test-mpi-short:
    <<: *ubuntu-2404
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-short

  test-serial-medium:
    <<: *ubuntu-2404
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-medium

  test-omp-medium:
    <<: *ubuntu-2404
    parallelism: 4
    environment:
      OMP_NUM_THREADS: '2'
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-medium
 
  test-mpi-medium:
    <<: *ubuntu-2404
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/mrchem
      - *tests-medium

workflows:
  build-and-test:
    jobs:
      - hold:
          type: approval
      - build-serial
      - test-serial-short:
          requires:
            - build-serial
      - build-omp
      - test-omp-short:
          requires:
            - build-omp
      - build-mpi
      - test-mpi-short:
          requires:
            - build-mpi
      - test-serial-medium:
          requires:
            - hold
            - build-serial
      - test-omp-medium:
          requires:
            - hold
            - build-omp
      - test-mpi-medium:
          requires:
            - hold
            - build-mpi